### PR TITLE
Switch To Streamer v2.9.4 And Some Bug Fixes

### PR DESCRIPTION
**Pull request by InterSstellar**
Hi, This PR is related to #116

### CODE REVIEW

**Comment by InterSstellar** [comment]
fixed ! Ready To merge

**Comment by InterSstellar** [comment]
Fixed The Bug and replace PlayerObjects With DynamicObjects In flymode.pwn
Ready To Merge !

**Comment by InterSstellar** [comment]
sorry i uploaded some files in filterscripts folder instead of tstudio folder -_-

**Comment by InterSstellar** [comment]
Finally. Ready To Merge =| xD -_-

**Comment by TechyJ416** [comment]
You on Discord? For some reason it doesn't call OnPlayerEditDynamicObject in a different gamemode's .pwn

**Comment by TechyJ416** [comment]
> Finally. Ready To Merge =| xD -_-

You on Discord? For some reason it doesn't call OnPlayerEditDynamicObject in a different gamemode's .pwn

**Comment by InterSstellar** [comment]
It's because of new streamer.
just add 
```
public OnPlayerEditObject(playerid, playerobject, objectid, response, Float:fX, Float:fY, Float:fZ, Float:fRotX, Float:fRotY, Float:fRotZ) return 0;
``` 
In Your Gamemode.pwn

if you want to use OnPlayerSelectDynamicObject add This code in your gamemode too:
```
public OnPlayerSelectObject(playerid, type, objectid, modelid, Float:fX, Float:fY, Float:fZ) return 0;
```

> You on Discord? 

yp My ID: InterStellar#5423

**Comment by TechyJ416** [comment]
I tried adding the first line before but nothing changed after adding select. Added on Discord. dotJay#4209

**Comment by InterSstellar** [comment]
return value for OnPlayerEditDynamicObject was 1 and that will prevent OnPlayerEditDynamicObject from begin called in gamemode.pwn.

I Changed It to 0. see if it works now

**Comment by TechyJ416** [comment]
Added:
`hook OnPlayerEditObject(playerid, playerobject, objectid, response, Float:fX, Float:fY, Float:fZ, Float:fRotX, Float:fRotY, Float:fRotZ) return 0;`
`hook OnPlayerSelectObject(playerid, type, objectid, modelid, Float:fX, Float:fY, Float:fZ) return 0;`

Changed all OnPlayerEditDynamicObject's to return with 0 in the gamemode files and it worked. Many thanks x

**Comment by InterSstellar** [comment]
@Crayder i Tested it and there was no problem. i made this PR 12 Days Ago. merge this if you have no problems with it ;D

**Pull request merged**
